language: python
python: 3.8
cache: pip
env:
  global:
    - REPO_NAME="${PWD##*/}"
    - IMAGE_NAME="${REPO_NAME}-${TRAVIS_BRANCH}"
    - AWS_PROFILE="default"
    - AWS_REGION="us-east-1"
install:
  # install packer
  - curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
  - sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
  - sudo apt-get update && sudo apt-get install packer
  # install awscli v2
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip
  - sudo ./aws/install
  # install other tools
  - pip install pre-commit travis-wait-improved ansible
before_script:
  - mkdir -p ~/.aws
  - echo -e "[default]\nregion=us-east-1\nsource_profile=default\nrole_arn=$AwsCfServiceRoleArn" > ~/.aws/config
  - echo -e "[default]\nregion=us-east-1\naws_access_key_id=$AwsTravisAccessKey\naws_secret_access_key=$AwsTravisSecretAccessKey" > ~/.aws/credentials
stages:
  - name: validate
  - name: deploy-branch
    if: type = push AND branch = master
  - name: deploy-tag
    if: tag =~ ^v[0-9]+\.[0-9]+\.[0-9]+
jobs:
  include:
    - stage: validate
      script:
        - pre-commit run --all-files
        - pushd src
        - echo "RepoName = ${REPO_NAME}"
        - echo "ImageName = ${IMAGE_NAME}"
        - echo "TravisBranch = ${TRAVIS_BRANCH}"
        - echo "AwsProfile = ${AWS_PROFILE}"
        - echo "AwsRegion = ${AWS_REGION}"
        - packer validate -var ImageName=${IMAGE_NAME} template.json
    - stage: deploy-branch
      script:
        - pushd src
        - travis-wait-improved --timeout 45m packer build -force -var AwsProfile=${AWS_PROFILE} -var AwsRegion=${AWS_REGION} -var ImageName=${IMAGE_NAME} template.json
    - stage: deploy-tag
      script:
        - pushd src
        - travis-wait-improved --timeout 45m packer build -force -var AwsProfile=${AWS_PROFILE} -var AwsRegion=${AWS_REGION} -var ImageName=${IMAGE_NAME} template.json
